from pathlib import Path

import pytest
import yaml

from oracle_bench.config import RuntimeConfig, load_config, validate_resolved_config

SAMPLE = Path(__file__).parents[1] / "configs" / "smoke.yaml"


def config_file(tmp_path, section, key, value):
    raw = yaml.safe_load(SAMPLE.read_text())
    raw.setdefault(section, {})[key] = value
    path = tmp_path / "config.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


@pytest.mark.parametrize("visibility", ["keep", "hide"])
def test_test_visibility_is_explicit_and_paths_are_config_relative(tmp_path, visibility):
    config = load_config(config_file(tmp_path, "task", "existing_tests", visibility))
    assert config.task.existing_tests == visibility
    assert config.task.prompt == str((tmp_path / "../prompts/unit-tests.md").resolve())
    assert config.output == str((tmp_path / "../runs").resolve())


def test_small_config_resolves_harness_defaults():
    config = load_config(SAMPLE)
    assert config.source.dataset == "lite"
    assert config.agent.harness == "codex"
    assert config.agent.provider == "openai"
    assert config.agent.credential_env == "OPENAI_API_KEY"
    assert config.agent.version
    assert config.runtime is None


@pytest.mark.parametrize(
    "section,key,value",
    [
        ("task", "existing_tests", "sometimes"),
        ("task", "generated_dir", "../outside"),
        ("task", "generated_dir", "/outside"),
        ("task", "generated_dir", ".git/hooks"),
        ("source", "revision", "main"),
        ("source", "kind", "git"),
        ("agent", "wall_seconds", 0),
        ("agent", "wall_seconds", True),
        ("agent", "typo", 123),
        ("agent", "provider", "unknown"),
    ],
)
def test_invalid_config_fails_before_starting_containers(tmp_path, section, key, value):
    with pytest.raises(ValueError):
        load_config(config_file(tmp_path, section, key, value))


@pytest.mark.parametrize("old_section", ["dataset", "environment", "harness"])
def test_verbose_schema_is_rejected(tmp_path, old_section):
    raw = yaml.safe_load(SAMPLE.read_text())
    raw[old_section] = {}
    path = tmp_path / "config.yaml"
    path.write_text(yaml.safe_dump(raw))
    with pytest.raises(ValueError, match="Unknown RunConfig settings"):
        load_config(path)


@pytest.mark.parametrize("section", ["runtime", "toolchain", "schema_version"])
def test_resolved_sections_cannot_be_supplied_as_input(tmp_path, section):
    raw = yaml.safe_load(SAMPLE.read_text())
    raw[section] = {} if section != "schema_version" else 2
    path = tmp_path / "config.yaml"
    path.write_text(yaml.safe_dump(raw))
    with pytest.raises(ValueError, match="generated by Oracle Bench"):
        load_config(path)


def test_generated_directory_is_checked_against_resolved_source_roots():
    config = load_config(SAMPLE)
    config.task.generated_dir = "requests/tests"
    config.runtime = RuntimeConfig(
        image="example/image:latest",
        source_roots=["requests"],
        import_modules=["requests"],
        existing_test_globs=["test_requests.py", "tests"],
    )
    with pytest.raises(ValueError, match="outside production source roots"):
        validate_resolved_config(config)


def test_resolved_run_lock_can_be_reloaded(tmp_path):
    config = load_config(SAMPLE)
    config.runtime = RuntimeConfig(
        image="example/image:latest",
        source_roots=["requests"],
        import_modules=["requests"],
        existing_test_globs=["test_requests.py", "tests"],
    )
    path = tmp_path / "config.resolved.yaml"
    path.write_text(yaml.safe_dump(config.to_dict()))

    reloaded = load_config(path, resolved=True)

    assert reloaded.schema_version == 2
    assert reloaded.require_runtime().image == "example/image:latest"
    assert reloaded.toolchain.coverage_version


def test_resolved_configuration_contains_no_credential_value(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "secret-test-value")
    config = load_config(SAMPLE)
    assert "secret-test-value" not in yaml.safe_dump(config.to_dict())
