from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path, PurePosixPath

import yaml

SCHEMA_VERSION = 2
SWEBENCH_DATASETS = {"lite": "princeton-nlp/SWE-bench_Lite"}
SWEBENCH_DATASET_REVISION = "6ec7bb89b9342f664a54a6e0a6ea6501d3437cc2"
CODEX_VERSION = "0.153.4"
CLAUDE_VERSION = "2.1.263"
NODE_IMAGE = "node:22.14.0-bookworm-slim"
PYTEST_VERSION = "7.4.4"
COVERAGE_VERSION = "7.6.1"


def repo_path(value: str) -> str:
    path = PurePosixPath(value)
    if (
        not value
        or path.is_absolute()
        or ".." in path.parts
        or str(path) == "."
        or ".git" in path.parts
        or value.startswith("-")
    ):
        raise ValueError(f"Expected a relative repository path, got {value!r}")
    return str(path)


@dataclass
class SourceConfig:
    instance: str
    kind: str = "swebench"
    dataset: str = "lite"
    revision: str = SWEBENCH_DATASET_REVISION
    split: str = "test"
    record: str | None = None

    @property
    def dataset_name(self) -> str:
        return SWEBENCH_DATASETS[self.dataset]


@dataclass
class AgentConfig:
    model: str
    harness: str = "codex"
    provider: str | None = None
    version: str | None = None
    multi_agent: bool = True
    wall_seconds: int = 900
    max_budget_usd: float = 0.25
    max_turns: int = 10
    auth: str = "oauth"

    @property
    def credential_env(self) -> str:
        if self.harness == "claude":
            return "ANTHROPIC_API_KEY" if self.auth == "api_key" else "CLAUDE_CODE_OAUTH_TOKEN"
        return "OPENROUTER_API_KEY" if self.provider == "openrouter" else "OPENAI_API_KEY"


@dataclass
class TaskConfig:
    prompt: str
    existing_tests: str = "keep"
    generated_dir: str = "oracle_tests"


@dataclass
class LimitsConfig:
    evaluation_seconds: int = 600
    setup_seconds: int = 1800
    memory: str = "4g"
    cpus: float = 2


@dataclass
class RuntimeConfig:
    """Resolved source runtime generated by a source adapter."""

    image: str
    source_roots: list[str]
    import_modules: list[str]
    existing_test_globs: list[str]
    platform: str = "linux/amd64"
    workdir: str = "/testbed"
    python: str = "/opt/miniconda3/envs/testbed/bin/python"
    rebuild: str = "python -m pip install --no-deps --no-build-isolation -e ."


@dataclass
class ToolchainConfig:
    """Oracle Bench implementation dependencies recorded with resolved runs."""

    node_image: str = NODE_IMAGE
    pytest_version: str = PYTEST_VERSION
    coverage_version: str = COVERAGE_VERSION


@dataclass
class RunConfig:
    source: SourceConfig
    agent: AgentConfig
    task: TaskConfig
    limits: LimitsConfig = field(default_factory=LimitsConfig)
    output: str = "runs"
    schema_version: int = SCHEMA_VERSION
    runtime: RuntimeConfig | None = None
    toolchain: ToolchainConfig = field(default_factory=ToolchainConfig)

    def to_dict(self) -> dict:
        return asdict(self)

    def require_runtime(self) -> RuntimeConfig:
        if self.runtime is None:
            raise RuntimeError("The source adapter has not resolved the repository runtime")
        return self.runtime


def _construct(cls, values):
    if not isinstance(values, dict):
        raise ValueError(f"{cls.__name__} must be a mapping")
    unknown = values.keys() - {f.name for f in fields(cls)}
    if unknown:
        raise ValueError(f"Unknown {cls.__name__} settings: {sorted(unknown)}")
    return cls(**values)


def _positive_number(value, name: str):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value <= 0:
        raise ValueError(f"{name} must be a positive number")


def _validate_runtime(config: RunConfig):
    runtime = config.runtime
    if runtime is None:
        return
    for name in ["source_roots", "import_modules"]:
        values = getattr(runtime, name)
        if not isinstance(values, list) or not all(isinstance(v, str) for v in values):
            raise ValueError(f"runtime.{name} must be a list of strings")
    runtime.source_roots = [repo_path(v) for v in runtime.source_roots]
    if not isinstance(runtime.existing_test_globs, list) or not all(
        isinstance(v, str) for v in runtime.existing_test_globs
    ):
        raise ValueError("runtime.existing_test_globs must be a list of strings")
    for pattern in runtime.existing_test_globs:
        if (
            not pattern
            or PurePosixPath(pattern).is_absolute()
            or ".." in PurePosixPath(pattern).parts
            or ".git" in PurePosixPath(pattern).parts
        ):
            raise ValueError(f"Invalid repository test glob {pattern!r}")
    if not runtime.source_roots:
        raise ValueError("runtime.source_roots cannot be empty")
    generated = PurePosixPath(config.task.generated_dir)
    for source in runtime.source_roots:
        root = PurePosixPath(source)
        if generated == root or generated in root.parents or root in generated.parents:
            raise ValueError("Generated tests must be outside production source roots")
    if not re.fullmatch(r"[A-Za-z0-9_./:@-]+", runtime.image):
        raise ValueError(f"Invalid container image reference {runtime.image!r}")
    for value in [runtime.python, runtime.workdir]:
        if not value.startswith("/") or "\n" in value:
            raise ValueError("Container Python and workdir must be absolute paths")


def validate_resolved_config(config: RunConfig):
    _validate_runtime(config)


def load_config(path: Path, *, resolved: bool = False) -> RunConfig:
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict):
        raise ValueError("Configuration must be a YAML mapping")
    raw = dict(raw)
    resolved_only = {"schema_version", "runtime", "toolchain"} & raw.keys()
    if resolved_only and not resolved:
        raise ValueError(
            f"Settings are generated by Oracle Bench and cannot be input: {sorted(resolved_only)}"
        )
    raw["source"] = _construct(SourceConfig, raw.get("source", {}))
    raw["agent"] = _construct(AgentConfig, raw.get("agent", {}))
    raw["task"] = _construct(TaskConfig, raw.get("task", {}))
    raw["limits"] = _construct(LimitsConfig, raw.get("limits", {}))
    if raw.get("runtime") is not None:
        raw["runtime"] = _construct(RuntimeConfig, raw["runtime"])
    if "toolchain" in raw:
        raw["toolchain"] = _construct(ToolchainConfig, raw["toolchain"])
    config = _construct(RunConfig, raw)

    if resolved and config.runtime is None:
        raise ValueError("Resolved configuration is missing runtime")

    if config.schema_version != SCHEMA_VERSION:
        raise ValueError(f"schema_version must be {SCHEMA_VERSION}")
    if config.source.kind != "swebench":
        raise ValueError("source.kind must be swebench")
    if config.source.dataset not in SWEBENCH_DATASETS:
        raise ValueError(f"Unknown SWE-bench dataset alias {config.source.dataset!r}")
    if not re.fullmatch(r"[0-9a-f]{40}", config.source.revision):
        raise ValueError("source.revision must be an immutable 40-character commit SHA")
    if not isinstance(config.source.instance, str) or not config.source.instance.strip():
        raise ValueError("source.instance cannot be empty")

    agent = config.agent
    if agent.harness not in {"codex", "claude"}:
        raise ValueError("agent.harness must be codex or claude")
    if agent.provider is None:
        agent.provider = "anthropic" if agent.harness == "claude" else "openai"
    if (agent.harness, agent.provider) not in {
        ("codex", "openai"),
        ("codex", "openrouter"),
        ("claude", "anthropic"),
    }:
        raise ValueError("Use codex with openai/openrouter, or claude with anthropic")
    if agent.version is None:
        agent.version = CLAUDE_VERSION if agent.harness == "claude" else CODEX_VERSION
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[a-zA-Z0-9.+-]*)?", agent.version):
        raise ValueError(f"Expected a pinned agent version, got {agent.version!r}")
    if not isinstance(agent.model, str) or not agent.model.strip():
        raise ValueError("agent.model cannot be empty")
    if not isinstance(agent.multi_agent, bool):
        raise ValueError("agent.multi_agent must be a boolean")
    if agent.auth not in {"oauth", "api_key"}:
        raise ValueError("agent.auth must be oauth or api_key")
    if (
        isinstance(agent.max_turns, bool)
        or not isinstance(agent.max_turns, int)
        or agent.max_turns <= 0
    ):
        raise ValueError("agent.max_turns must be a positive integer")

    if config.task.existing_tests not in {"keep", "hide"}:
        raise ValueError("task.existing_tests must be keep or hide")
    config.task.generated_dir = repo_path(config.task.generated_dir)
    for value, name in [
        (agent.wall_seconds, "agent.wall_seconds"),
        (agent.max_budget_usd, "agent.max_budget_usd"),
        (config.limits.evaluation_seconds, "limits.evaluation_seconds"),
        (config.limits.setup_seconds, "limits.setup_seconds"),
        (config.limits.cpus, "limits.cpus"),
    ]:
        _positive_number(value, name)
    for version in [config.toolchain.pytest_version, config.toolchain.coverage_version]:
        if not re.fullmatch(r"\d+\.\d+\.\d+(?:[a-zA-Z0-9.+-]*)?", version):
            raise ValueError(f"Expected a pinned package version, got {version!r}")
    if not re.fullmatch(r"[A-Za-z0-9_./:@-]+", config.toolchain.node_image):
        raise ValueError(f"Invalid container image reference {config.toolchain.node_image!r}")

    base = path.resolve().parent
    config.task.prompt = str((base / config.task.prompt).resolve())
    config.output = str((base / config.output).resolve())
    if config.source.record:
        config.source.record = str((base / config.source.record).resolve())
    _validate_runtime(config)
    return config
